# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            My Portfolio
tagline:          'A collection of my open source projects and publications'
description:      'A personal website showcasing my open source projects, work experience, and publications.'
url:              https://97harsh.github.io
baseurl:          /

author:
  name:           'Harsh Sharma'
  url:            https://97harsh.github.io

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/97harsh
