# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Harsh Sharma
tagline:          'A collection of my open source projects and publications'
description:      'Progress lies in the pursuit of better problems, sometimes powered by data.'
url:              https://97harsh.github.io
baseurl:          /

author:
  name:           'Harsh Sharma'
  url:            https://97harsh.github.io
  github:         97harsh
  email:          harshsrharsh@gmail.com
  linkedin:       sharma-ai

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/97harsh

# Meta Description
meta_description: 'A personal website showcasing my open source projects, work experience, and publications.'
