# Site settings
title: Harsh Sharma
description: Showcasing my projects
baseurl: /blog # This is the subpath of your site, e.g. /blog
url: https://97harsh.github.io
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
gems:
  - jekyll-paginate