# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Harsh Sharma
tagline:          'A collection of my open source projects and publications'
description:      'A personal website showcasing my open source projects, work experience, and publications.'
url:              https://97harsh.github.io
baseurl:          /

author:
  name:           'Harsh Sharma'
  url:            https://97harsh.github.io
  github:         97harsh
  email:          harshsrharsh@gmail.com
  linkedin:       sharma97

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/97harsh
