# Site settings
title: 'Harsh Sharma'
description: ''
url: ''
baseurl: ''
profilepic: ''
bkimage: '/images/bk1.jpg'
google_analytics: ''
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Thomas Zühlke'
  email: harshsrharsh@gmail.com
#  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  97harsh
#  linkedin_username:  thomas-zühlke-889182165
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
